name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build API
      run: go build -v ./ecom-api/.
      
    - name: Build Backend
      run: go build -v ./ecom-backend/.

    - name: Test API
      run: go test -v ./ecom-api/.
    
    - name: Test Backend
      run: go build -v ./ecom-backend/.
