name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    
    - name: Init mod
      run: cd ./ecom-api/ && go mod download
      
    - name: Build API
      run: go build -v .

    - name: Test API
      run: go test -v .
